### ISSUE TITLE
Is there any demo for the use of this project?

### ISSUE THREAD

**Issue by flyforfreedom** [flipkart-incubator/hbase-object-mapper#10]
I would like to use this project in my Spring Boot application, but didn't know how to config HBase in my bootstrap.yaml file, is anyone there could give me an example？Thanks!

**Comment by m-manu** [comment]
We don't have a sample application that is open-source. You can check the [TestsAbstractHBDAO.java](https://github.com/flipkart-incubator/hbase-orm/blob/master/src/test/java/com/flipkart/hbaseobjectmapper/testcases/TestsAbstractHBDAO.java) for code snippets.

Essentially, it boils down to this:
 * Construct a `Configuration` object using `HBaseConfiguration.create()` method. If `hbase-site.xml` and other configuration files on your web service nodes have all details, it should work out-of-the-box. If not, you call `configuration.set*` methods to set correct configuration.
 * Construct a `Connection` object using `ConnectionFactory` and above.
* Create entity classes. Create classes `YourDAO1` `YourDAO2` etc. by extending `AbstractHBDAO`. Instantiate these classes once in your entire application lifecycle.
* Use these DAO classes in your application
