### ISSUE TITLE
Dynamic column names

### ISSUE THREAD

**Issue by oemergenc** [flipkart-incubator/hbase-object-mapper#11]
Hi, thanks for this library. It helps me a lot. 

Is there any way to specify dynamic column names?

**Comment by m-manu** [comment]
Can you elaborate a bit with example? I can help.

**Comment by oemergenc** [comment]
Hi, of course i can. 
I would like to be able to specify dynamic column qualifiers. Currently the `HBColumn` annotation allows tp specify a static column name, e.g.:
```
public class Dependents implements Serializable {
    private Integer dependId;
}

@HBTable(name = "citizens", families = {@Family(name = "main"), @Family(name = "optional", versions = 10)})
public class Citizen implements HBRecord<String> {
    private static final String ROWKEY_DELIMITER = "#";
    @HBRowKey
    private String citizenId;
    @HBColumn(family = "optional", column = "dependents")
    private Dependents dependents; // Your own class
...
}
```

To take full advantage of hbase horizontal scaling capabilities it would be great if it would be possible to save multiple `dependents` under unique column names. This would allow to instantly access any `dependent` using an unique identifier.

I am thinking about something like this:
```
@HBTable(name = "citizens", families = {@Family(name = "main"), @Family(name = "optional", versions = 10)})
public class Citizen implements HBRecord<String> {
    private static final String ROWKEY_DELIMITER = "#";
    @HBRowKey
    private String citizenId;
    @HBColumn(family = "optional", qualifierField = "dependId")
    private List<Dependents> dependents; 
...
}
```

Where `dependId` must be a member variable of `Dependents` and the value of the member variable will be used for the column qualifier. In this example this could result in column named:
```
- optional:dependents#1234
- optional:dependents#9876
- optional:dependents#952
```
This would allow to leverage hbase full capabilities to instantly access a specific dependent of a customer using an unique identifier.

**Comment by oemergenc** [comment]
I finally released a small library with this feature, find it here:

https://github.com/oemergenc/hbase-orm-extensions
