### ISSUE TITLE
Does this library support kerberos authentication?

### ISSUE THREAD

**Issue by francesco-clementi-92** [flipkart-incubator/hbase-object-mapper#19]
Does this library support kerberos authentication?
Is yes, how can I implement it?

Moreover, in the README there is
"So, it is recommended that you create Connection instance once and use it for the entire life cycle of your program across all the DAO classes that you create (such as above)"
Could you explain better how to do it?

**Comment by m-manu** [comment]
Regarding Kerberos:
We've not tested this library with Kerberos. You'll have to try it yourself.

Regarding `Connection`:
Here is a good article:
https://hbase.apache.org/2.2/apidocs/org/apache/hadoop/hbase/client/Connection.html

HBase `Connection` creation is a resource-intensive operation. So here is the recommended way to do it:

1. Create `Connection` at the start of your web service (or long running job). This can be done either manually or in your dependency injection providers classes
2. Use this connection to create your DAO classes and access HBase -- This part is quite fast
3. Don't close `Connection` till end of your program! (`Connection` being `AutoCloseable` may be confusing)
