### ISSUE TITLE
How do you handle un-normalized columns?

### ISSUE THREAD

**Issue by dalamar66** [flipkart-incubator/hbase-object-mapper#2]
If you have an object that contains a Map of let's say himself.

Menu:
- String parent_name
- String parent_url
- Map String, Menu

To have in HBase: parent_name, parent_url, menu1_name, menu1_url, menu2_name, menu2_url ....

Is this taken care of? Or it can be implemented?

**Comment by m-manu** [comment]
This feature does not exist in this library. But you can implement this by forking this and making changes in `HBObjectMapper` class.
