### ISSUE TITLE
good ，good project

### ISSUE THREAD

**Issue by outman1234** [flipkart-incubator/hbase-object-mapper#4]

**Comment by outman1234** [comment]
i need more document~~~~

**Comment by m-manu** [comment]
@outman1234 Let me know for which specific part you need more documentation.

**Comment by m-manu** [comment]
The documentation on the [main repo page](../) is elaborate enough. Below each of the code examples, there are links to test case java sources files where actual code using the methods in library are available. 

Apart from that Javadoc for each class and method is quite extensive
