### ISSUE TITLE
Tests still working?

### ISSUE THREAD

**Issue by tedfar** [flipkart-incubator/hbase-object-mapper#6]
When I download your project and did clean install with maven and I get exceptions.  I get the same exception when trying to write a test DAO of my own off of your base one.

Exception in thread "main" com.flipkart.hbaseobjectmapper.exceptions.ImproperHBTableAnnotationExceptions$MissingHBTableAnnotationException: Class com.flipkart.hbaseobjectmapper.HBRecord is missing HBTable annotation

Basically this line in WrappedHBTable returns null which leads to this exception:

final HBTable hbTable = clazz.getAnnotation(HBTable.class);
        
Are you seeing this too?  when you do a fresh mvn clean install on your package?

**Comment by m-manu** [comment]
@tedfar `master`, `1.7`, `1.6`, `1.5.1`, `1.5` -- all of them are passing when doing `mvn clean install` using Maven 3.2.5 and javac 1.7.0_75 & javac 1.8.0_131.

So, can provide me output of `mvn --version` on the machine you ran `mvn clean install`?

**Comment by tedfar** [comment]
@m-manu, that's strange.  Here you go:

Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T12:39:06-07:00)
Maven home: /opt/apache-maven-3.5.0
Java version: 1.8.0_65, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"

I had to change the location of your horton repository to get it to work.  Adding POM file too.  

[hbm-pom.zip](https://github.com/flipkart-incubator/hbase-object-mapper/files/1136420/hbm-pom.zip)

**Comment by tedfar** [comment]
Was my bad.  I have it working now.  You throw exceptions but I missed the comment that they were expected.  Thanks for the reply.

**Comment by m-manu** [comment]
@tedfar Yes, test cases are extensive. The 'exception' cases also are tested explicitly. I'm glad you were able to build is successfully.
