### ISSUE TITLE
Inherited abstract class design

### ISSUE THREAD

**Issue by tedfar** [flipkart-incubator/hbase-object-mapper#7]
I would like to have the rowkey management (and attributes) in a base, abstract class.  The base abstract class would have @HBRowKey and some @HBColumn annotated fields, but the sub-class would have the @HBTable annotation and some other @HBColumns.  

As you probably know this doesn't work.  your code looks for annotations using getDeclaredFields which is only the last(sub) class.  Do you have a ticket on this or any plans to support this use case?  Otherwise I can change it, but wanted to check with you first.  thx.  Great framework!

**Comment by m-manu** [comment]
Yes, I plan to implement "inherit `HBColumn` from base class" in a way similar to that of [MappedSuperClass](https://docs.jboss.org/hibernate/jpa/2.1/api/javax/persistence/MappedSuperclass.html) annotation. I don't have timelines right now. If you happen to take it up sooner than me, please do send a pull request. 

By the way, "inheriting row key handling" works even now. Also, `@HBRowKey` is only an informational annotation.

**Comment by tedfar** [comment]
@m-manu thanks for the reply.  Yeah for now I just added a simple getDeclaredFields and getDeclaredMethod methods to the main object mapper class that climbs the hierarchy.  It always does it opposed to annotating when to do it.  It works great.   

It was throwing a fatal exception for me for the rowkey not being in the sub-class.   Even with commentary "(how else would you construct the row key for HBase record?)" :)  It also failed with composeRowKey not being in the sub-class.

I need to clean it up and write tests and I'll let you know.  thanks.

**Comment by m-manu** [comment]
@tedfar This feature is now partially available in [v1.10](https://github.com/flipkart-incubator/hbase-orm/releases/tag/v1.10).
