### ISSUE TITLE
Changing the Codec with HBAbstractDAO

### ISSUE THREAD

**Issue by tedfar** [flipkart-incubator/hbase-object-mapper#8]
Hi,

I have a custom rowkey object so I want to use the JavaStreamCodec instead of the BestSuitCodec.  
I have several DAO classes inheriting from HBAbstractDAO.   Two questions for you.

1. In HBAbstractDAO, you have
    protected static final HBObjectMapper hbObjectMapper = new HBObjectMapper();
Which makes it impossible to change the codec of the mapper for any sub-class of this class.  

2. I can work around this by removing the final and static (not all of the sub-classes use the same serialization theme).  So my question is why is this static?  It doesn't seem to hold state.  is there a big initialization cost?  Is there a downside to each sub-class having its own copy?

If there is a better way to accomplish what I want, please let me know.  thx.

**Comment by m-manu** [comment]
>  So my question is why is this static? It doesn't seem to hold state. is there a big initialization cost? Is there a downside to each sub-class having its own copy?

The initialisation can be high, depending on your `Codec`. In your case, since the `Codec` is `JavaStreamCodec`, it shouldn't be a problem. 

Generally, it is recommended not to keep multiple copies of Jackson's `ObjectMapper` (it's hard on GC)

**Comment by tedfar** [comment]
Thanks for the quick reply.  Yes, I agree on singletons of ObjectMapper.  I'll make that static in the codec if I use it.  thx.

**Comment by m-manu** [comment]
This will be tracked from here: https://github.com/flipkart-incubator/hbase-object-mapper/projects/3

Closing this issue now.

**Comment by m-manu** [comment]
@tedfar This feature is now available in `v1.8`.
