### ISSUE TITLE
AbstractHBDAO should takes Connection instead of Configuration

### ISSUE THREAD

**Issue by panthony** [flipkart-incubator/hbase-object-mapper#9]
The `Table` interface may not be thread-safe but `Connection` is, and it is costly to create.

Since the only usage of `Configuration` is to create a `Connection` they should be swapped.

This way a user could create a single `Connection` instance for its app (and close it when necessary.) and have multiple instance of `DAO` (per-thread).

**Comment by m-manu** [comment]
I'll add two more constructors: one that takes `Table` and another that takes `Connection`. That should solve more usecases.

**Comment by panthony** [comment]
The `Table` is inferred by `HBTable` annotation. I don't think it make sense to have a constructor that takes a `Table`.

That would mean you can pass a `Table` that is not the one declared by the record class.

**Comment by m-manu** [comment]
You're right, only the constructor that takes `Connection` is needed. 

It doesn't make sense to have a constructor that takes `Table` and then verify whether the instance of `Table` matches record class.

**Comment by m-manu** [comment]
[v1.11](https://github.com/flipkart-incubator/hbase-orm/releases/v1.11) is now released. It provides above and few other features. 

To use: https://mvnrepository.com/artifact/com.flipkart/hbase-object-mapper/1.11
